### PR TITLE
Fix pry-remote.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* It does not work with foreman and the current version of Rails.

This change addresses the need by:

* Lock version of `pry-byebug` to version `1.3.3` per this comment:
https://github.com/Mon-Ouie/pry-remote/issues/61#issuecomment-98565289

Side effects:

* We can only use an older version of byebug.

### CODE REVIEW

**Comment by bbrock25** [comment]
;+1:

**Comment by Mrjaco12** [comment]
👍

**Comment by samcdavid** [comment]
Do you have to do a gem install to get Gemfile.lock to update for that specific version?

**Comment by squaresurf** [comment]
@samcdavid I don't think so. I just ran `bundle install` for Empact and it worked great.

**Comment by samcdavid** [comment]
👍

**Pull request merged**
