### PR TITLE
Add seedbank gem.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* [Seedbank](https://github.com/james2m/seedbank) allows you to
structure your Rails seed data instead of having it all dumped into
one large file.

This change addresses the need by:

* Add seedbank gem.
* Update `db/seeds.rb` with comment about seedbank.

### CODE REVIEW

**Comment by bbrock25** [comment]
I personally feel that this one should be left to the users of the project to decide

**Comment by Mrjaco12** [comment]
I kind of agree with Bill. I think we should be using seeds to help with development. But I don't think I care to be too opinionated about what tool we do it with. Especially considering the possibility of using a fixture type of seeding which has some varied benefits.

**Comment by samcdavid** [comment]
Yea, I'm on the fence with this one as well. I can definitely see the benefits of `seedbank` as we are using it on other projects but I wouldn't say that it is a requirement and should be a part of our raygun template. That is really dependent on the project for how much seed data is needed.

**Comment by squaresurf** [comment]
My thought was that this would encourage good seeding practices. I also have a hard time seeing a project that shouldn't have this gem. In the end, the PR was more of a suggestion. Feel free to reopen this if anyone wants to continue the conversation.

**Pull request closed without merging**
