### PR TITLE
Add atomic cms to railgun rails template

### PR DESCRIPTION
**Pull request by mirceacr**
https://trello.com/c/Ol3WTWfR/55-2-scamper-template

WHY? So we can use it with the CMS installed when flashing it out

HOW? Install, configure, test etc

### CODE REVIEW

**Comment by Mrjaco12** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1:

**Comment by squaresurf** [comment]
:clap: great work @samcdavid 

I wonder why hound was so late to the party.

**Comment by samcdavid** [comment]
I have no idea. Mircea and I can tackle these though :smile:

**Pull request merged**
