### PR TITLE
Add Rollbar handler for low level puma errors.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* Rollbar hasn't loaded yet so it won't send errors in middleware for
example.

This change addresses the need by:

* Add Rollbar handler to the puma config.

Side effects:

* Errors in middleware will be sent to Rollbar.

### CODE REVIEW

**Comment by Mrjaco12** [comment]
:+1:

**Comment by samcdavid** [comment]
Is this currently in use on another project?

**Comment by Mrjaco12** [comment]
We just added it to ASME. See [here](https://github.com/spartansystems/asme/blob/master/config/puma.rb)

**Comment by samcdavid** [comment]
:+1:

**Pull request merged**
