### PR TITLE
Add rollbar js.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* So we get rollbar notifications for our client side javascript.

This change addresses the need by:

* Add the rollbar javascript snippet.
* Restructure javascript assets so that we don't include admin
javascript etc on the frontend where it is not needed.

### CODE REVIEW

**Comment by squaresurf** [comment]
Please note that I restructured the javascript asset paths a little. Please feel free to ask me any questions as to why :smile:. The TL;DR is that it makes it so that admin assets (e.g. angular) don't get served to the frontend.

**Comment by bbrock25** [comment]
maybe restructuring the asset paths should be in a separate pr? I'm fine with the rollbar config stuff, but I'm not sure I like the imposing of opinions on javascript paths. It seems like it could be a great solution for our CMS, but i'm not sure that its something that would/should be the default on all of our projects.

**Comment by jasontwong** [comment]
I'm a fan of javascript path changes in general. In my personal/side projects I do this all the time as to separate "admin" and "marketing" areas. But I keep it in line with my layouts. So if I have a application layout vs a dashboard layout, then I usually create two javascript asset paths. I don't have enough domain knowledge, but if there are different layouts, having different paths makes sense to me. My $0.02

**Comment by Mrjaco12** [comment]
@jasontwong the only domain knowledge that you need for this project is that we use this repo as a template for all future rails projects. So do you think the proposed changes would be useful 100% of the time? 90%? 50%? And at what threshold would rather not have it be a default. I agree with Bill's opinion that the rollbar and asset restructure should be separate PRs as rollbar should be in ASAP while the asset structure might merit some more debate.

**Comment by jasontwong** [comment]
Whoops. I thought for some reason this was related to Atomic CMS. I agree that the structure should be part of a separate PR. And to clarify my answer, currently the template doesn't really seem to need separate javascript paths since there's only one layout.

**Comment by squaresurf** [comment]
@bbrock25 the basic template currently includes jquery multiple times as well as other duplicate libraries if you use the atomic cms which I would venture is over 90% of the projects that will be generated from this project. For example, the most recently generated app using this currently downloads 1.7 MB of javascript assets. I quickly commented out the `//= require_tree .` statement and it then changed to 391 KB. That is over 4 times the amount of network usage which just ends up in waste and a slower experience. The proposed path changes are simple so that you can include any frontend assets in one of the frontend dirs, depending on whether or not it is a vendor file, then it works without including other assets that aren't needed and are slowing down the site. The real question here is if you want to remember to restructure your paths for over 90% of the projects we're doing. By doing this sort of restructuring here in our template, we all get to stop worrying about efficiency gains like this and focus on the business domain that we're writing for.

All that being said, I will open another PR with just the rollbar javascript as we already have quite a bit of discussion going on here regarding the javascript paths.

**Comment by bbrock25** [comment]
@squaresurf yeah man, I get it. less is more :) I have quite a bit of frustration myself with the asset pipeline and am very much in support of us cleaning it up in future projects.

**Comment by jasontwong** [comment]
The largest issue with this approach that I've encountered is when using generators. Generators will always dump the js files into the `app/assets/javascripts` folder and we have to manually move it. Unless there's an option I don't know about.

**Comment by samcdavid** [comment]
Shouldn't vendor assets be served from the vendor folder anyway?

**Comment by squaresurf** [comment]
@samcdavid ? My path modifications add a `frontend` folder to the vendor directories so that the frontend can include vendor assets without including all the admin assets.

**Comment by squaresurf** [comment]
Ok, everyone, this is now only a PR for the rollbar.js.

I'm gonna drop the javascript path reorganization. I would :heart: to see someone else open a PR that solves the **real** issue of including too many assets from the admin. Having every page request 1.7 MB of javascript, of which 1.3 MB is not needed at all, slows down page loads and impacts our clients. It **needs** to be addressed.

**Comment by Mrjaco12** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1:

**Comment by samcdavid** [comment]
:+1:

**Pull request merged**
