### PR TITLE
Add linters

### PR DESCRIPTION
**Pull request by Mrjaco12**
I want to get this one in before others so we have good linting defaults!

Why:

We require linting of code via codeclimate or hound so
it is useful to have linters in the repo for local linting
and these tools can use our linters as well for maximum
lint customization.

This change addresses the need by:

Added default configs from LintRoller repo

### CODE REVIEW

**Comment by squaresurf** [comment]
You mention codeclimate in the PR description, but there is not a codeclimate config nor a eslint config.

**Comment by squaresurf** [comment]
You could copy the one from ASME.

**Comment by Mrjaco12** [comment]
In the effort to distance ourselves from codeclimate, I'd rather not.

**Comment by squaresurf** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1:

**Pull request merged**
