### PR TITLE
Up line length to 120.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* It uses more valuable screen real estate without getting out of
control.

This change addresses the need by:

* Up the rubocop line length max to 120.
* Add the other two rubocop line length settings that were missing.

### CODE REVIEW

**Comment by bbrock25** [comment]
80 is better :+1:

**Comment by Mrjaco12** [comment]
:+1: No it's not.

**Comment by bbrock25** [comment]
I guess that either is fine :)

**Comment by samcdavid** [comment]
That is why in the template I compromised to use 100 because I preferred 80 as well but looks like that is going out the window.

**Comment by squaresurf** [comment]
I'm going to open another PR that brings in the latest rubocop config from LintRoller.

**Pull request closed without merging**
