### PR TITLE
Flesh out bin wrapper scripts further.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* Having a consistent set of scripts makes it easier to get started on
any project no matter the language/framework (i.e. RoR, Node, PHP,
etc) or the solution that is being used to run the server (i.e. local,
docker, vagrant, otto, etc). We should always have a `bin/up`,
`bin/init`, and `bin/down` so that it lessens the strain on the team
when we change how things are ran.

This change addresses the need by:

* Add `bin/down`.
* Add `bin/init`.
* Move README init instructions into a script.
* Update README.
* Call `bin/down` at the beginning of the `bin/up` script in case the
server crashed and left stuff running.

### CODE REVIEW

**Comment by Mrjaco12** [comment]
:+1:

**Comment by Mrjaco12** [comment]
Given Issue #4 we might want to hold off on this until we have a resolution.

**Comment by Mrjaco12** [comment]
We should move the user create part of the init script to after the DB has been started.

**Comment by Mrjaco12** [comment]
It also looks like you may need to add a sleep after starting the DB if the next operations depend on it being up.

**Comment by Mrjaco12** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1:

**Pull request merged**
