### PR TITLE
Rubocop -a more *file ruby files.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* They weren't addressed when we moved to using double quotes.

This change addresses the need by:

* Run `rubocop -a` on Gemfile, Rakefile, and Vagrantfile.

### CODE REVIEW

**Comment by squaresurf** [comment]
@samcdavid this feels like we're diverging from the rails community by using double quotes. If you still like this please give me our :+1:

**Comment by squaresurf** [comment]
It should be noted that there are other rubocop fixes besides quotes.

**Comment by Mrjaco12** [comment]
:+1:

**Comment by samcdavid** [comment]
:+1:

**Comment by bbrock25** [comment]
I would like to voice here that running `rubocop -a` and committing those changes erases all commit history and replaces that with a robot. Not the most valuable when looking for reasoning behind a design decision. I'm sure its fine on this project, since its mostly generated code, but I'm pretty wary of using rubocop like this.

**Comment by squaresurf** [comment]
It does **not** erase **all** commit history, just the most recent blame which is useful for anything that is not a template like this project. To be honest, this was not my first choice, I would have rather updated the rubocop config to use single quotes. This is better than starting a project that has a linter config that is in conflict with the vast majority of it's code. Otherwise as the actual project work is done, you will see meaningless commits all throughout it's history fixing the quotes which makes it harder to see the work done on the real business domain.

If you ever do want to see the history, you can run `git log -p path/to/any/file` and see the commit messages alongside the code as it changed.

**Comment by bbrock25** [comment]
@squaresurf yeah, I figured that there was a way around it, thanks for sharing. That all does makes sense. I just prefer not to run robots to "auto correct" my code is all. I'd rather have some somewhat trivial discrepancies than have to hunt down the history. Either way, :+1:. Glad to have this project moving.

**Pull request merged**
