### PR TITLE
Update rails.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* There were some security patches released.

This change addresses the need by:

* Change rails version to be optimistic versioning in the Gemfile.
* Run `bundle update rails`

### CODE REVIEW

**Comment by bbrock25** [comment]
:+1:

**Comment by jasontwong** [comment]
:+1:

**Comment by squaresurf** [comment]
@bbrock25 @jasontwong I had to also update `rspec-rails` as RSpec was broken with the latest version of rails.

**Comment by squaresurf** [comment]
@bbrock25 @jasontwong I'd love to get another :+1: from you both before merging :smil:

**Comment by samcdavid** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1: @squaresurf sorry that I missed that on the first time through, I though I remembered seeing that on twitter or something.

**Comment by jasontwong** [comment]
:+1:

**Pull request merged**
