### PR TITLE
CMS Hotfix

### PR DESCRIPTION
**Pull request by samcdavid**
Why:

* For some reason the admin edit buttons had a rollbar config in it...

This change addresses the need by:

* Put actual admin edit buttons in the edit buttons partial.
* Update rollbar version.
* Add page name and path to admin index listing.

### CODE REVIEW

**Comment by mirceacr** [comment]
:+1:

**Comment by squaresurf** [comment]
:+1:

**Comment by Mrjaco12** [comment]
Did you double check the rollbar js was good?

**Comment by samcdavid** [comment]
I ran `bundle exec rake rollbar:test` and it gave me the A-OK.

**Pull request merged**
