### PR TITLE
Move application layout to be a slim file.

### PR DESCRIPTION
**Pull request by squaresurf**
Why:

* It is useful to have Optimizely ready to go since you need allow
  Optimizely to iframe the site as well as include a js file.

This change addresses the need by:

* Add the js file if the env var is set.
* Allow optimizely to iframe the site if the env var is set.

### CODE REVIEW

**Comment by bbrock25** [comment]
did you intend to include the optimizely bit here?

**Comment by Mrjaco12** [comment]
:+1:

**Comment by samcdavid** [comment]
Since there are references to the optimizely env var, should it be included in `.env.sample`?

**Comment by squaresurf** [comment]
@bbrock25 I just updated the PR to have a title and description like I intended. I did the slim move in another commit so it would be easier to read a diff of what was changed before it moved.

**Comment by squaresurf** [comment]
@samcdavid that is a great idea. I'll add it to the .env.sample file.

**Comment by squaresurf** [comment]
@samcdavid done :smile:

**Comment by samcdavid** [comment]
:+1:

**Comment by squaresurf** [comment]
@bbrock25 are you cool with this?

**Pull request merged**
