### PR TITLE
Move rack-timeout to production group

### PR DESCRIPTION
**Pull request by Mrjaco12**
Why:

* It breaks pry in development

This change addresses the need by:

* Moves rack-timeout to production group

### CODE REVIEW

**Comment by squaresurf** [comment]
:+1:

**Comment by bbrock25** [comment]
:+1:

**Comment by samcdavid** [comment]
bueller?

**Comment by Mrjaco12** [comment]
Shit I don't remember what this was about. There's a conflict. Maybe it already happened? I'll look into it.

**Comment by Mrjaco12** [comment]
OK @samcdavid @bbrock25 @squaresurf 

I've updated this to fix conflicts and also added a strict version to angular-js cause I know we've been running into that problem a few times. Please re-review and I'll get it in.

**Comment by squaresurf** [comment]
:+1: 

As I recall, having rack-timeout in the main gem group caused issues with pry as it killed the connection after 15 seconds in pry.

**Comment by samcdavid** [comment]
:+1: I am adding the strict version for angular in another PR as well, good thing it is the same version :smile:

**Comment by Mrjaco12** [comment]
Thanks boyos.

**Pull request merged**
